### ISSUE TITLE
TypeError: list indices must be integers or slices, not NoneType

### ISSUE THREAD

**Issue by bulhiCzar** [vsys-host/shkeeper.io#17]
helm-charts
commit 00c9520d31a619aa9901a31805910c0bb01e35f7 - error
I rolled back to the committee f0b4312bb16e881d4fee29168ab8a373c9eac08f , everything works there

` kubectl -n shkeeper logs tron-shkeeper-7784758d54-nmvsx  --tail 100`
```
10.42.0.167 - bitcoind-user [01/May/2023:04:59:40 +0000] "POST /USDC/status HTTP/1.1" 200 81 "-" "python-requests/2.28.1"
[2023-05-01 04:59:40,970] WARNING <ThreadPoolExecutor-0_0 Thread>: Exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/app/api/views.py", line 48, in get_status
    last_seen_block_num = bs.get_last_seen_block_num()
  File "/app/app/block_scanner.py", line 87, in get_last_seen_block_num
    last_block_num = self.get_current_height()
  File "/app/app/block_scanner.py", line 98, in get_current_height
    n = ConnectionManager.client().get_latest_block_number()
  File "/app/app/connection_manager.py", line 29, in client
    return cls.get_instance().get_client()
  File "/app/app/connection_manager.py", line 48, in get_client
    client = self.get_client_for_server_id(server_id)
  File "/app/app/connection_manager.py", line 52, in get_client_for_server_id
    provider = HTTPProvider(self.servers[server_id]['url'])
TypeError: list indices must be integers or slices, not NoneType

```

**Comment by dmytro-samoylenko** [comment]
Hello,
Please try with a latest chart version 1.2.35.
