### ISSUE TITLE
ETH/BNB seem to be broken in latest release.

### ISSUE THREAD

**Issue by DeprecatedLuke** [vsys-host/shkeeper.io#39]
Exceptions that occur:
```
192.168.220.32 - bitcoind-user [18/Nov/2023:12:23:39 +0000] "POST /BNB-USDT/balance HTTP/1.1" 200 119 "-" "python-requests/2.28.1"
[2023-11-18 12:23:39,337] WARNING: Exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/app/api/views.py", line 62, in get_status
    last_checked_block_number = int(pd.value)
AttributeError: 'NoneType' object has no attribute 'value'

192.168.220.32 - bitcoind-user [18/Nov/2023:12:36:39 +0000] "POST /ETH-USDC/status HTTP/1.1" 200 70 "-" "python-requests/2.28.1"
023-11-18 12:30:39,513] WARNING: Exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/app/api/views.py", line 60, in get_status
    last_checked_block_number = int(pd.value)
AttributeError: 'NoneType' object has no attribute 'value'
```

ETH fullnode is fully synced.

BNB fullnode deployment isn't configured correctly in helm chart:
```
INFO [11-18|12:34:36.798] Looking for peers                        peercount=0 tried=54  static=0
WARN [11-18|12:34:39.283] Served eth_chainId                       conn=192.168.219.206:56258 reqid=0 t="22.993Âµs" err="chain not synced beyond EIP-155 replay-protection fork block" X-Forwarded-For=nil
WARN [11-18|12:34:39.283] Served eth_chainId                       conn=192.168.219.206:56258 reqid=0 duration="22.292Âµs" err="chain not synced beyond EIP-155 replay-protection fork block"
WARN [11-18|12:34:39.285] Served eth_chainId                       conn=192.168.219.206:56260 reqid=0 t="8.175Âµs"  err="chain not synced beyond EIP-155 replay-protection fork block" X-Forwarded-For=nil
WARN [11-18|12:34:39.285] Served eth_chainId                       conn=192.168.219.206:56260 reqid=0 duration="7.744Âµs"  err="chain not synced beyond EIP-155 replay-protection fork block"
WARN [11-18|12:34:41.498] Snapshot extension registration failed   peer=182c008a err="peer connected on snap without compatible eth support"
```

**Comment by DeprecatedLuke** [comment]
TRC is also failing:
```
[2023-11-18 21:24:00,130] WARNING <ThreadPoolExecutor-1_0 Thread>: Block 211678: Transaction info extraction error: 'ret': {'signature': ['7efafe5c08925c06188df1d49624cff76a485f84df54f2b4a1536c4e7aa06b5999b8d026e1334f9b11ed4146ceb9035098e7adcbdc33a69fc309ded5460121f400'], 'txID': '09ff53a7f423545d55e45bd7c8630c5eb2ff6742c4ddb4e41bffe74fed01ff36', 'raw_data': {'contract': [{'parameter': {'value': {'owner_address': 'TQAMGfjv1yxA6vx1QZZwwp5qUB8cqeEZ1m', 'votes': [{'vote_address': 'TGj1Ej1qRzL9feLTLhjwgxXF4Ct6GTWg2U', 'vote_count': 4000}, {'vote_address': 'TDGmmTC7xDgQGwH4FYRGuE7SFH2MePHYeH', 'vote_count': 10000}, {'vote_address': 'TYVJ8JuQ6ctzCa2u79MFmvvNQ1U2tYQEUM', 'vote_count': 5000}]}, 'type_url': 'type.googleapis.com/protocol.VoteWitnessContract'}, 'type': 'VoteWitnessContract'}], 'ref_block_bytes': '3adb', 'ref_block_hash': '268a3940dd0bd45c', 'expiration': 1530527037000}, 'raw_data_hex': '0a023adb2208268a3940dd0bd45c40c8ec94d4c52c5aa4010804129f010a30747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e566f74655769746e657373436f6e7472616374126b0a15419bad3d414cc29948940f025a55f71bfc7fc12e67121a0a15414a193c92cd631c1911b99ca964da8fd342f4cddd10a01f121a0a1541243accc5241d97ce79272b06952ee88a34d8e1f910904e121a0a1541f70386347e689e6308e4172ed7319c49c0f66e0b108827'}
[2023-11-18 21:24:00,130] ERROR <ThreadPoolExecutor-1_0 Thread>: Block 211678: Failed to scan: 'ret'
Traceback (most recent call last):
  File "/app/app/block_scanner.py", line 149, in scan
    raise e
  File "/app/app/block_scanner.py", line 136, in scan
    info = self.get_tx_info(tx)
  File "/app/app/block_scanner.py", line 181, in get_tx_info
    status = tx['ret'][0]['contractRet']
KeyError: 'ret'
[2023-11-18 21:24:00,130] INFO <Block Scanner Thread>: Some blocks failed, retrying chunk 211677 - 211678

```

**Comment by yukonet** [comment]
Hello,

You can check following issue: https://github.com/vsys-host/ethereum-shkeeper/issues/1
Adding LAST_BLOCK_LOCKED=False variable fixes the error "AttributeError: 'NoneType' object has no attribute 'value'" for both BNB and ETH (add this variable only after the fullnode is fully synchronised)

To be able run a BNB fullnode you should sync it from a snapshot (https://docs.bnbchain.org/docs/validator/fullnode)

To resolve issue with Tron you can switch to using Shkeeper Tron Fullnode server (http://fullnode.tron.shkeeper.io/) or download and sync a self-hosted Tron fullnode from a snapshot.

**Comment by DeprecatedLuke** [comment]
Full node deployments should probably be split into its own helm chart. Or should be included in troubleshoot section in the docs.

**Comment by dmytro-samoylenko** [comment]
Hello,

Thank you for suggestions.  I'm not sure the fullnode deployment will be useful on its own.
