### ISSUE TITLE
how to deploy shkeeper.io

### ISSUE THREAD

**Issue by anycolo** [vsys-host/shkeeper.io#43]
I've tried to enable tron and tron-related coins like this:

```
tron_fullnode:
  enabled: true
  url: http://fullnode.tron.shkeeper.io

trx:
  enabled: true
usdt:
  enabled: true
usdc:
  enabled: true

```
But the server status in the wallet tab is Offline. Is this expected? There are some tron and java related processes running.

I've also tried adding ethereum support:

```
eth_fullnode:
  enabled: true
  url: http://ethereum:8545
  mainnet: true
  nodeSelector: {}
  tolerations: []

ethereum_shkeeper:
  image: vsyshost/ethereum-shkeeper:1.0.9

eth:
  enabled: true
eth_usdt:
  enabled: true
eth_usdc:
  enabled: true
```
But the status is also offline. I can see geth synchronizing in the background. Is this expected?
There is no documentation available, i've gathered these settings from older github issues, so they are probably out-ot-date.

**Comment by yukonet** [comment]
Hello,
If you are going to use a shkeeper public node  for tron you should use next values:

```
tron_fullnode:
  enabled: false
  url: http://fullnode.tron.shkeeper.io

trx:
  enabled: true
usdt:
  enabled: true
usdc:
  enabled: true
```

For ETH it is hard to say what is going wrong without logs.
Could you share it?

**Comment by anycolo** [comment]
How do i share logs for eth?

**Comment by anycolo** [comment]
```
Defaulted container "geth" out of: geth, prysm-beacon, nginx
INFO [03-07|12:07:24.506] Imported new potential chain segment     number=19,383,191 hash=be308c..965b3f blocks=1     txs=286       mgas=28.089  elapsed=313.630ms   mgasps=89.561  snapdiffs=6.65MiB   triedirty=1020.95MiB
INFO [03-07|12:07:24.587] Chain head was updated                   number=19,383,191 hash=be308c..965b3f root=82f0de..7f1017 elapsed=6.79458ms
INFO [03-07|12:07:35.902] Imported new potential chain segment     number=19,383,192 hash=90ef40..b0c3bd blocks=1     txs=111       mgas=9.041   elapsed=109.941ms   mgasps=82.239  snapdiffs=6.68MiB   triedirty=1021.19MiB
INFO [03-07|12:07:35.961] Chain head was updated                   number=19,383,192 hash=90ef40..b0c3bd root=8959bc..5aecbe elapsed=2.901088ms
INFO [03-07|12:07:48.614] Imported new potential chain segment     number=19,383,193 hash=e76592..c1f13e blocks=1     txs=128       mgas=12.558  elapsed=142.613ms   mgasps=88.054  snapdiffs=6.71MiB   triedirty=1020.72MiB
INFO [03-07|12:07:48.680] Chain head was updated                   number=19,383,193 hash=e76592..c1f13e root=f5ead4..77f2d2 elapsed=4.107129ms
INFO [03-07|12:08:00.730] Imported new potential chain segment     number=19,383,194 hash=362774..cca5f0 blocks=1     txs=224       mgas=19.846  elapsed=210.965ms   mgasps=94.074  snapdiffs=6.77MiB   triedirty=1021.75MiB
INFO [03-07|12:08:00.806] Chain head was updated                   number=19,383,194 hash=362774..cca5f0 root=582eb5..b6694f elapsed=5.658421ms
INFO [03-07|12:08:12.719] Imported new potential chain segment     number=19,383,195 hash=5e40c4..9f9781 blocks=1     txs=141       mgas=8.045   elapsed=97.390ms    mgasps=82.610  snapdiffs=6.79MiB   triedirty=1022.17MiB
INFO [03-07|12:08:12.778] Chain head was updated                   number=19,383,195 hash=5e40c4..9f9781 root=044486..295355 elapsed=3.840449ms
INFO [03-07|12:08:24.546] Imported new potential chain segment     number=19,383,196 hash=0e98b3..254200 blocks=1     txs=243       mgas=16.771  elapsed=208.089ms   mgasps=80.596  snapdiffs=6.85MiB   triedirty=1021.58MiB
INFO [03-07|12:08:24.618] Chain head was updated                   number=19,383,196 hash=0e98b3..254200 root=79c22e..1fcaa1 elapsed=5.458884ms
INFO [03-07|12:08:38.155] Imported new potential chain segment     number=19,383,197 hash=40e737..97ef4d blocks=1     txs=192       mgas=15.678  elapsed=151.090ms   mgasps=103.768 snapdiffs=6.89MiB   triedirty=1022.14MiB
INFO [03-07|12:08:38.229] Chain head was updated                   number=19,383,197 hash=40e737..97ef4d root=134b5d..5d7ac7 elapsed=3.929942ms
INFO [03-07|12:08:49.689] Imported new potential chain segment     number=19,383,198 hash=549a05..bf9ebe blocks=1     txs=124       mgas=11.311  elapsed=135.697ms   mgasps=83.358  snapdiffs=6.92MiB   triedirty=1021.80MiB
INFO [03-07|12:08:49.773] Chain head was updated                   number=19,383,198 hash=549a05..bf9ebe root=0c6db2..4bcacb elapsed=2.75637ms
INFO [03-07|12:09:00.769] Imported new potential chain segment     number=19,383,199 hash=25df8d..9fa690 blocks=1     txs=128       mgas=7.367   elapsed=98.205ms    mgasps=75.014  snapdiffs=6.95MiB   triedirty=1021.32MiB
INFO [03-07|12:09:00.825] Chain head was updated                   number=19,383,199 hash=25df8d..9fa690 root=807a55..8387fc elapsed=2.685875ms
INFO [03-07|12:09:13.749] Imported new potential chain segment     number=19,383,200 hash=85a8b3..d3c6e8 blocks=1     txs=320       mgas=29.085  elapsed=265.291ms   mgasps=109.634 snapdiffs=7.02MiB   triedirty=1022.54MiB
INFO [03-07|12:09:13.830] Chain head was updated                   number=19,383,200 hash=85a8b3..d3c6e8 root=91a350..d49cc7 elapsed=7.354801ms

```

**Comment by anycolo** [comment]
Maybe this is related?
```

10.42.0.84 - bitcoind-user [07/Mar/2024:12:12:38 +0000] "POST /ETH-USDC/balance HTTP/1.1" 200 35 "-" "python-requests/2.28.1"
[2024-03-07 12:12:38,341] WARNING: Exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/app/api/views.py", line 59, in get_status
    last_checked_block_number = int(pd.value)
AttributeError: 'NoneType' object has no attribute 'value'

[2024-03-07 12:12:38,342] WARNING: Exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/app/api/views.py", line 59, in get_status
    last_checked_block_number = int(pd.value)
AttributeError: 'NoneType' object has no attribute 'value'

10.42.0.84 - bitcoind-user [07/Mar/2024:12:12:38 +0000] "POST /ETH-USDT/status HTTP/1.1" 200 70 "-" "python-requests/2.28.1"

```

**Comment by yukonet** [comment]
Hello,

You can check following issue: https://github.com/vsys-host/ethereum-shkeeper/issues/1
Adding LAST_BLOCK_LOCKED=False variable fixes the error "AttributeError: 'NoneType' object has no attribute 'value'" for ETH (add this variable only after the fullnode is fully synchronised)

**Comment by anycolo** [comment]
I did it like this
```
ethereum_shkeeper:
  image: vsyshost/ethereum-shkeeper:1.0.9
  env:
    - name: "LAST_BLOCK_LOCKED"
      value: "False"

```

Then ran
```
helm repo update
helm upgrade -f values.yaml shkeeper vsys-host/shkeeper

```

But ethereum wallet status is still offline.

**Comment by anycolo** [comment]
So, does this work or not? Do i need to pay for support? I want to try to make this work.

**Comment by chuonglv** [comment]
> So, does this work or not? Do i need to pay for support? I want to try to make this work.

Do you have any updates? I also have the same problem

**Comment by yukonet** [comment]
You can use command `kubectl -n shkeeper edit deploy ethereum-shkeeper` to edit deployment and add 
```
- name: LAST_BLOCK_LOCKED 
  value: "False" 
```
to the `env` section of each container

Before doing this, make sure the full node is fully syncronized

**Comment by anycolo** [comment]
I did this, then the server status changed to green: :

Sync In Progress (73873 blocks behind)

The number doesn't decrease. I've removed the last_block_locked env variable, but it stayed like that.
I can see this in logs:
[2024-03-23 22:32:17,543] ERROR: Last checked block 19427274 is bigger than last block 19426586 in blockchain
NoneType: None
[2024-03-23 22:32:19,553] ERROR: Last checked block 19427274 is bigger than last block 19426586 in blockchain
NoneType: None
[2024-03-23 22:32:21,563] ERROR: Last checked block 19427274 is bigger than last block 19426586 in blockchain
NoneType: None

Do i need to start over ?

**Comment by yukonet** [comment]
Judging from the provided log, your full node has rolled back and is not catching up with the blockchain, you need to check it first

**Comment by anycolo** [comment]
How do i remove it and start over?

**Comment by yukonet** [comment]
Usually ethereum full node catches up with the blockchain on its own. 
Could you provide more logs of ethereum-shkeeper and ethereum ?

What exactly do you want to remove and start over?

**Comment by anycolo** [comment]
Hello,

I have no idea why, but it synced on its own after a few days. Everything looks green now.
