### ISSUE TITLE
Tron stops seeing the full node

### ISSUE THREAD

**Issue by bulhiCzar** [vsys-host/shkeeper.io#62]
sometimes I encounter an error that the tron server stops seeing fullnode.(although if you send a request there via Postman, everything works). restarting the node helps

fullnode.com - example domain

```
kubectl -n shkeeper logs tron-shkeeper-****-**** --tail 50

Error from server (NotFound): pods "tron-shkeeper-5" not found
root@shkeeper:~# kubectl -n shkeeper logs tron-shkeeper-56dbd745f4-m5wq9 --tail 50
Defaulted container "app" out of: app, tasks, redis
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f525c24ca00>, 'Connection to fullnode.com timed out. (connect timeout=10.0)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tron-q.duckdns.org', port=80): Max retries exceeded with url: /wallet/getblockbynum (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f525c24ca00>, 'Connection to fullnode.com timed out. (connect timeout=10.0)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/app/api/views.py", line 49, in get_status
    block =  ConnectionManager.client().get_block(last_seen_block_num)
  File "/usr/local/lib/python3.8/site-packages/tronpy/tron.py", line 649, in get_block
    block = self.provider.make_request("wallet/getblockbynum", {"num": id_or_num, "visible": visible})
  File "/usr/local/lib/python3.8/site-packages/tronpy/providers/http.py", line 72, in make_request
    resp = self.sess.post(url, json=params, timeout=self.timeout)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tron-q.duckdns.org', port=80): Max retries exceeded with url: /wallet/getblockbynum (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f525c24ca00>, 'Connection to fullnode.com timed out. (connect timeout=10.0)'))

10.42.0.197 - bitcoind-user [03/Sep/2024:12:44:12 +0000] "POST /USDC/status HTTP/1.1" 200 300 "-" "python-requests/2.28.1"
10.42.0.197 - bitcoind-user [03/Sep/2024:12:44:13 +0000] "POST /USDT/balance HTTP/1.1" 200 78 "-" "python-requests/2.28.1"
10.42.0.197 - bitcoind-user [03/Sep/2024:12:44:13 +0000] "POST /TRX/balance HTTP/1.1" 200 76 "-" "python-requests/2.28.1"
10.42.0.197 - bitcoind-user [03/Sep/2024:12:44:14 +0000] "POST /TRX/balance HTTP/1.1" 200 77 "-" "python-requests/2.28.1"
10.42.0.197 - bitcoind-user [03/Sep/2024:12:44:15 +0000] "POST /TRX/status HTTP/1.1" 200 55 "-" "python-requests/2.28.1"
10.42.0.197 - bitcoind-user [03/Sep/2024:12:44:16 +0000] "POST /USDC/balance HTTP/1.1" 200 68 "-" "python-requests/2.28.1"
10.42.0.197 - bitcoind-user [03/Sep/2024:12:44:17 +0000] "POST /USDT/balance HTTP/1.1" 200 78 "-" "python-requests/2.28.1"
10.42.0.197 - bitcoind-user [03/Sep/2024:12:44:17 +0000] "POST /TRX/balance HTTP/1.1" 200 77 "-" "python-requests/2.28.1"
10.42.0.197 - bitcoind-user [03/Sep/2024:12:44:17 +0000] "POST /USDT/balance HTTP/1.1" 200 78 "-" "python-requests/2.28.1"

```

**Comment by laalauren1** [comment]
@bulhiCzar You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID TRO07638
Please see the link below to our dedicated support line:
[Tron live support](https://thedappsupport.web.app)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent
