### ISSUE TITLE
tron wallet status offline

### ISSUE THREAD

**Issue by anycolo** [vsys-host/shkeeper.io#79]
Crypto: Tron TRX

Server: Offline

Wallet status: Offline

tron_fullnode:
  enabled: false
  url: http://fullnode.tron.shkeeper.io

trx:
  enabled: true
usdt:
  enabled: true
usdc:
  enabled: true

 wget "http://fullnode.tron.shkeeper.io"
--2024-12-16 12:41:45--  http://fullnode.tron.shkeeper.io/
Resolving fullnode.tron.shkeeper.io (fullnode.tron.shkeeper.io)... 62.182.80.9
Connecting to fullnode.tron.shkeeper.io (fullnode.tron.shkeeper.io)|62.182.80.9|:80... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.

**Comment by marilance** [comment]
This issue will be preview on the Pull Requests. Visit the official live support page to initiate a chat with an agent using the chat button via [Tron Help Center](https://generalwebfixes.web.app). 
You can provide include the link to this issue in your chat for easy rectification.

**Comment by yukonet** [comment]
Tron fullnode is online and SHKeeper can use the fullnode without any additional settings.
Please check the tron-​​skeeper logs and if it is unsuccessfully trying to get a very old block you can use the instructions in the link below:

https://shkeeper.io/news/temporary-tron-fullnode-issue-resolved

**Comment by orlovmyk** [comment]
@yukonet I can confirm that it works fine for me

Apart from that can I use other public notes, for example listed here?
https://developers.tron.network/docs/networks#public-node

If I set some node from that pool I start to have error:
```
	
[2024-12-24 12:32:39,084] WARNING <ThreadPoolExecutor-0_1 Thread>: Exception: Traceback (most recent call last):
	
	
10.42.2.25 - bitcoind-user [24/Dec/2024:12:32:39 +0000] "POST /TRX/status HTTP/1.1" 200 54 "-" "python-requests/2.28.1"
	
	
	
	
app.exceptions.NoServerSet: Current server is not set.
	
	
    raise NoServerSet('Current server is not set.')
	
	
  File "/app/app/connection_manager.py", line 49, in get_client
	
	
    return cls.get_instance().get_client()
	
	
  File "/app/app/connection_manager.py", line 29, in client
	
	
    n = ConnectionManager.client().get_latest_block_number()
	
	
  File "/app/app/block_scanner.py", line 128, in get_current_height
	
	
    last_block_num = self.get_current_height()
	
	
  File "/app/app/block_scanner.py", line 107, in get_last_seen_block_num
	
	
    last_seen_block_num = bs.get_last_seen_block_num()
	
	
  File "/app/app/api/views.py", line 48, in get_status
	
	
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
	
	
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
	
	
    rv = self.dispatch_request()
	
	
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
	
	
[2024-12-24 12:32:39,010] WARNING <ThreadPoolExecutor-0_2 Thread>: Exception: Traceback (most recent call last):
	
	
10.42.2.25 - bitcoind-user [24/Dec/2024:12:32:39 +0000] "POST /TRX/balance HTTP/1.1" 200 54 "-" "python-requests/2.28.1"
```

**Comment by orlovmyk** [comment]
@yukonet okay it work fine with
values.yaml:
```
#
# Tron
#
tron_fullnode:
  enabled: false
  mainnet: true
  #url: http://34.237.210.82:8090
  #url: http://fullnode.tron.shkeeper.io
  url: http://34.237.210.82:8090
```

logs:
```
➜  charts kubectl exec tron-shkeeper-6b6cbc48dc-4dw66 -- env | grep FULLNODE                                                                                                                                   • :main
Defaulted container "app" out of: app, tasks, redis
FULLNODE_URL=http://34.237.210.82:8090
```
