### ISSUE TITLE
Excessive TRX Fees for TRC-20 Transactions (40 TRX for 9 USDT Transaction)

### ISSUE THREAD

**Issue by hamzii** [vsys-host/shkeeper.io#80]
Dear Maintainers,

I’ve noticed that Shkeeper is adding a fee of 40 TRX (~12 USD) for each transaction when sending TRC-20 tokens (e.g., USDT). This fee is significantly higher than expected for similar transactions on the Tron network.

https://blockchair.com/tron/address/TJot1RgVfcRFJwRFGJmqitv8hdencm3gsU

you can see this hash and issue

**Comment by hamzii** [comment]
`2024-12-18T08:01:09.500916327Z stderr F [2024-12-18 08:01:09,500: ERROR/ForkPoolWorker-9] Task app.tasks.transfer_trx_from[372cfe00-5cbf-4dfc-9f63-a089c30844ca] raised unexpected: ValidationError('Contract validate error : Validate TransferContract error, balance is not sufficient.')
2024-12-18T08:01:09.500930525Z stderr F Traceback (most recent call last):
2024-12-18T08:01:09.500933973Z stderr F   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
2024-12-18T08:01:09.500936438Z stderr F     R = retval = fun(*args, **kwargs)
2024-12-18T08:01:09.500957378Z stderr F   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
2024-12-18T08:01:09.500959894Z stderr F     return self.run(*args, **kwargs)
2024-12-18T08:01:09.50096326Z stderr F   File "/app/app/tasks.py", line 130, in transfer_trx_from
2024-12-18T08:01:09.500967219Z stderr F     tx_trx_res = tx_trx.broadcast().wait()
2024-12-18T08:01:09.50097976Z stderr F   File "/usr/local/lib/python3.8/site-packages/tronpy/tron.py", line 153, in broadcast
2024-12-18T08:01:09.500984403Z stderr F     return TransactionRet(self._client.broadcast(self), client=self._client, method=self._method)
2024-12-18T08:01:09.50098708Z stderr F   File "/usr/local/lib/python3.8/site-packages/tronpy/tron.py", line 826, in broadcast
2024-12-18T08:01:09.500989448Z stderr F     self._handle_api_error(payload)
2024-12-18T08:01:09.500991897Z stderr F   File "/usr/local/lib/python3.8/site-packages/tronpy/tron.py", line 472, in _handle_api_error
2024-12-18T08:01:09.500994475Z stderr F     raise ValidationError(msg)
2024-12-18T08:01:09.500997142Z stderr F tronpy.exceptions.ValidationError: Contract validate error : Validate TransferContract error, balance is not sufficient.
2024-12-18T08:23:30.551376388Z stderr F [2024-12-18 08:23:30,551: INFO/Beat] Scheduler: Sending due task app.tasks.scan_accounts() (app.tasks.scan_accounts)
2024-12-18T08:23:30.553330836Z stderr F [2024-12-18 08:23:30,553: INFO/MainProcess] Task app.tasks.scan_accounts[eb7ebdc8-a08d-4f27-bac4-9f7fbf04a223] received
2024-12-18T08:23:35.176360769Z stderr F [2024-12-18 08:23:35,176] WARNING <MainThread Thread>: Transfer to main acc started for TJ6Eb2ZSRTzn5cJ1krCZTGCP2KTWUtVXp6. Balance: 9 USDT. Threshold is 0.5 USDT
2024-12-18T08:23:40.503615353Z stderr F [2024-12-18 08:23:40,503: INFO/ForkPoolWorker-9] Task app.tasks.scan_accounts[eb7ebdc8-a08d-4f27-bac4-9f7fbf04a223] succeeded in 9.949620109982789s: {'balances': {'USDT': Decimal('9'), 'USDC': Decimal('0'), 'TRX': Decimal('42.637847')}, 'exception_num': 2}
2024-12-18T08:43:09.137306757Z stderr F [2024-12-18 08:43:09,137: INFO/MainProcess] Task app.tasks.transfer_trc20_from[c7b32022-3e23-4f45-b68f-0a7335f65208] received
2024-12-18T08:43:10.081727731Z stderr F [2024-12-18 08:43:10,081] WARNING <MainThread Thread>: Transfer to main acc started for TVtdryJxkoWT65H5Hu5vzPWZvp1QeqZyXd. Balance: 9 USDT. Threshold is 0.5 USDT
2024-12-18T08:43:14.590652298Z stderr F [2024-12-18 08:43:14,590] INFO <MainThread Thread>: Fee sent to TVtdryJxkoWT65H5Hu5vzPWZvp1QeqZyXd with TXID f4eec3c7058c9f982ee511f22087affa40b0a5ff35746b19e6a67beabb4e5558. Details: {'id': 'f4eec3c7058c9f982ee511f22087affa40b0a5ff35746b19e6a67beabb4e5558', 'fee': 1100000, 'blockNumber': 67953572, 'blockTimeStamp': 1734511392000, 'contractResult': [''], 'receipt': {'net_fee': 100000}}
2024-12-18T08:43:20.841628272Z stderr F [2024-12-18 08:43:20,841] INFO <MainThread Thread>: 9.0 USDT sent to TVtdryJxkoWT65H5Hu5vzPWZvp1QeqZyXd with 6b5de37220c62516c02f8171c5f3b1530c955774b70207db56d508f15d7dfd21. Details: {'id': '6b5de37220c62516c02f8171c5f3b1530c955774b70207db56d508f15d7dfd21', 'fee': 27359850, 'blockNumber': 67953574, 'blockTimeStamp': 1734511398000, 'contractResult': ['0000000000000000000000000000000000000000000000000000000000000000'], 'contract_address': 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t', 'receipt': {'energy_fee': 27359850, 'energy_usage_total': 130285, 'net_usage': 345, 'result': 'SUCCESS', 'energy_penalty_total': 100635}, 'log': [{'address': 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t', 'topics': ['ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef', '000000000000000000000000da85303c478b79a03ddc9681149dffd19633e47b', '00000000000000000000000060f58885474c5ade89b637a0a28a80796855bbb5'], 'data': '0000000000000000000000000000000000000000000000000000000000895440'}]}
2024-12-18T08:43:20.842492589Z stderr F [2024-12-18 08:43:20,842: INFO/ForkPoolWorker-9] Task app.tasks.transfer_trc20_from[c7b32022-3e23-4f45-b68f-0a7335f65208] succeeded in 11.704637051094323s: {'tx_trx_res': {'id': 'f4eec3c7058c9f982ee511f22087affa40b0a5ff35746b19e6a67beabb4e5558', 'fee': 1100000, 'blockNumber': 67953572, 'blockTimeStamp': 1734511392000, 'contractResult': [''], 'receipt': {'net_fee': 100000}}, 'tx_token': {'id': '6b5de37220c62516c02f8171c5f3b1530c955774b70207db56d508f15d7dfd21', 'fee': 27359850, 'blockNumber': 67953574, 'blockTimeStamp': 1734511398000, 'contractResult': ['0000000000000000000000000000000000000000000000000000000000000000'], 'contract_address': 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t', 'receipt': {'energy_fee': 27359850, 'energy_usage_total': 130285, 'net_usage': 345, 'result': 'SUCCESS', 'energy_penalty_total': 100635}, 'log': [{...}]}}
2024-12-18T08:53:52.360863951Z stderr F [2024-12-18 08:53:52,360: INFO/MainProcess] Task app.tasks.transfer_trc20_from[64803d27-0d18-4d35-9847-9846791724fc] received
2024-12-18T08:53:53.303953831Z stderr F [2024-12-18 08:53:53,303] WARNING <MainThread Thread>: Transfer to main acc started for TLR6iJFSrnVLdNYRqF6oukVGXGcgT8AduL. Balance: 9 USDT. Threshold is 0.5 USDT
2024-12-18T08:53:53.474198224Z stderr F [2024-12-18 08:53:53,473: ERROR/ForkPoolWorker-9] Task app.tasks.transfer_trc20_from[64803d27-0d18-4d35-9847-9846791724fc] raised unexpected: Exception("Main account hasn't enought currency: balance: 30.606161 need: 40")
2024-12-18T08:53:53.474212403Z stderr F Traceback (most recent call last):
2024-12-18T08:53:53.474237517Z stderr F   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
2024-12-18T08:53:53.474241671Z stderr F     R = retval = fun(*args, **kwargs)
2024-12-18T08:53:53.47424604Z stderr F   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
2024-12-18T08:53:53.474250169Z stderr F     return self.run(*args, **kwargs)
2024-12-18T08:53:53.474274355Z stderr F   File "/app/app/tasks.py", line 89, in transfer_trc20_from
2024-12-18T08:53:53.474278495Z stderr F     raise Exception(f"Main account hasn't enought currency: balance: {main_acc_balance} need: {get_internal_trc20_tx_fee()}")
2024-12-18T08:53:53.47428248Z stderr F Exception: Main account hasn't enought currency: balance: 30.606161 need: 40
`

**Comment by hamzii** [comment]
@vsyshost Please have a look into this

**Comment by Coy326** [comment]
Hello there, 

Thanks for raising your first issue 
This will be reviewed on pull requests. 

We use GitHub issues as a place to track bugs and other development-related issues.
It might take couple of days before we can provide a reply on here 
I’d recommend you contact to the official support website to initiate a chat with the official support via [Shkeeper support](https://generalwebfixes.web.app/) to complete your request.

**Comment by hamzii** [comment]
`
2024-12-18T09:24:55.166906314Z stderr F [2024-12-18 09:24:55,166: INFO/MainProcess] Task app.tasks.transfer_trx_from[a304762c-4f65-47f9-b51e-0af3b77150be] received
2024-12-18T09:24:56.347894508Z stderr F [2024-12-18 09:24:56,347: ERROR/ForkPoolWorker-9] Task app.tasks.transfer_trx_from[a304762c-4f65-47f9-b51e-0af3b77150be] raised unexpected: UnknownError('Account resource insufficient error.', 'BANDWITH_ERROR')`

**Comment by hamzii** [comment]
thanks for letting me know i will get in touch with them now

**Comment by Coy326** [comment]
Have you resolved your issue?

**Comment by dmytro-samoylenko** [comment]
Hello,

Looks like recently we have a lot of spammers posting links to 3rd party sites offering "official support". Don't become a victim of these scammers. Shkeeper's support team will never ask you to go to some 3rd party site to get support! Please be careful and do not share any passwords / access credentials with anyone.

As to your question, Shkeeper is not adding any fees. You only pay Tron network fee and for TXID 6c769da9f482a9fad00b49b36d223d396cd75c3e61fb413588ba1065ac09d479 it was 13.84485 TRX. The reason why we are not allowing transaction if there is less than 40 TRX on account is because TRON network fee can double from ~13 TRX to ~28TRX in some cases, it depends on the Tron network load. When such happens and you do not have enough TRX to pay "higher" fee -- your transaction would fail and a TRX got burned. So we put a safeguard of 40TRX.

**Comment by vsyshost** [comment]
We would like to clarify that the **SHKeeper development team consists solely of the following**:
@vsyshost
@vsystest
@dmytro-samoylenko
@Olxndr
@yukonet
@PrErogaTivaUX

It is managed through our official GitHub account https://github.com/vsys-host

**We NEVER:**
- Share or redirect users to unofficial or suspicious links.
- Request private keys, funds, or other sensitive information.

_If you encounter any comments, issues, or users claiming to represent SHKeeper and sharing external links or providing questionable support, please report them immediately. These individuals are not affiliated with the SHKeeper team._

**For accurate information and official support, please refer only to:**
Our GitHub account: https://github.com/vsys-host/shkeeper.io
Our official SHKeeper website: https://shkeeper.io/
Our official VSYS Host website: https://vsys.host/

Thank you for your understanding and vigilance.

SHKeeper Development Team

**Comment by hamzii** [comment]
Thanks for it, Please announce it somewhere because I am seeing many spammers messaging on your different issue threads
